
import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'ru' | 'en';
  setLanguage: (lang: 'ru' | 'en') => void;
  t: (key: string) => string;
}

const translations = {
  ru: {
    shop_name: 'Barsh Shop',
    catalog: 'Каталог',
    about: 'О нас',
    about_author: 'Об авторе',
    cart: 'Корзина',
    home: 'Главная',
    search_placeholder: 'Поиск товаров...',
    all_categories: 'Все категории',
    stickers: 'Стикеры',
    keychains: 'Брелки',
    postcards: 'Открытки',
    figures_3d: '3D Фигурки',
    add_to_cart: 'В корзину',
    price_from: 'от',
    rubles: 'руб.',
    exclusive_stickers: 'Эксклюзивные стикеры',
    from_andrey_barsh: 'от Andrey Barsh',
    hero_subtitle: 'Уникальные дизайны для ваших проектов',
    featured_products: 'Популярные товары',
    empty_cart: 'Корзина пуста',
    total: 'Итого',
    checkout: 'Оформить заказ',
    quantity: 'Количество',
    remove: 'Удалить',
    about_title: 'О магазине Barsh Shop',
    about_description: 'Мы специализируемся на создании уникальных стикеров, брелков, открыток и 3D фигурок. Наши дизайны отличаются высоким качеством и оригинальностью.',
    items_in_cart: 'товаров в корзине',
    new_collection: 'Новая коллекция',
    hero_title: 'Эксклюзивные дизайны от ',
    hero_brand: 'Barsh',
    hero_description: 'Откройте для себя уникальные стикеры, брелки, открытки и 3D фигурки, созданные с любовью и вниманием к деталям.',
    shop_now: 'Перейти в магазин',
    learn_more: 'Узнать больше',
    why_choose_us: 'Почему выбирают нас',
    features_subtitle: 'Мы предлагаем лучшее качество и сервис',
    quality_products: 'Качественные товары',
    quality_desc: 'Все наши продукты изготовлены из высококачественных материалов',
    fast_delivery: 'Быстрая доставка',
    delivery_desc: 'Доставляем заказы по всей России в кратчайшие сроки',
    secure_payment: 'Безопасная оплата',
    payment_desc: 'Гарантируем безопасность всех платежных операций',
    featured_subtitle: 'Самые популярные товары нашего магазина',
    view_all: 'Смотреть все',
    view_product: 'Подробнее',
    back_to_catalog: 'Назад к каталогу',
    description: 'Описание',
    high_quality_materials: 'Высококачественные материалы',
    unique_design: 'Уникальный дизайн',
    fast_shipping: 'Быстрая доставка',
    satisfaction_guarantee: 'Гарантия качества',
    delivery_info: 'Информация о доставке',
    free_delivery_over: 'Бесплатная доставка при заказе от',
    delivery_time: 'Срок доставки:',
    business_days: 'рабочих дней',
    return_policy: 'Возврат в течение',
    days: 'дней',
    no_products_found: 'Товары не найдены',
    // Checkout translations
    checkout_title: 'Оформление заказа',
    customer_info: 'Информация о покупателе',
    first_name: 'Имя',
    last_name: 'Фамилия',
    phone_number: 'Номер телефона',
    email: 'Email',
    delivery_address: 'Адрес доставки',
    city: 'Город',
    enter_city: 'Введите город',
    street_address: 'Адрес',
    enter_address: 'Введите адрес',
    postal_code: 'Почтовый индекс',
    map_placeholder: 'Карта для выбора адреса',
    address_selection: 'Выберите точный адрес на карте',
    order_items: 'Товары в заказе',
    order_summary: 'Итого к оплате',
    subtotal: 'Стоимость товаров',
    delivery_cdek: 'Доставка СДЭК',
    delivery_post: 'Доставка Почтой России',
    delivery_method: 'Метод доставки',
    out_of_servise: 'Временно не работает',
    calculating: 'Расчёт...',
    place_order: 'Оформить заказ',
    // About page translations
    about_greeting: 'Привет! Меня зовут Андрей Барщевский',
    about_intro: 'Мой псевдоним - Barsh. Я 2D/3D художник, аниматор и автор блога, где делюсь своим опытом, процессами работы, мыслями о индустрии и искусстве.',
    about_location: 'Я из Санкт-Петербурга. Рисовать начал в 2019 году, осваивал академический рисунок и живопись около 2 лет в художественной студии. В это же время учился работать в Photoshop. Тогда же я впервые открыл Blender 3d.',
    about_school: 'В старших классах школы увлекся камерами и цветокоррекцией. Брал простые заказы по графическому дизайну для соц сетей. Начал изучать After Effects, Premier pro, Davinci.',
    about_3d: 'В 2022 году возобновил изучение 3D графики, некоторые из моих работ начали набирать просмотры на Sketchfab и Artstation. Появились интересные заказы.',
    about_clients: 'Первый опыт работы с иностранными заказчиками.',
    about_youtube: 'Веду канал на YouTube с 2023 года.',
    work_inspiration_title: 'Мои работы и вдохновение',
    work_intro: 'Все моё творчество - это смесь 2D и 3D арта. Мне нравится сам процесс создания визуала. Такого, который передает настроение, возможно смысл или удовольствие, если речь про дизайн.',
    work_simplicity: 'В рисовании мне не нравится использовать много технологий и инструментов. Бывает достаточно одного слоя и кисти. Через простоту я сохраняю частичку магии.',
    work_tools: 'Но при работе над 3D графикой или в видеопродакшене я всегда ищу лучшие комбинации инструментов.',
    work_inspiration: 'Все что окружает меня и происходит со мной дает мне вдохновение. Личный опыт намного ценнее. Исходя из него можно развивать новые идеи.',
    work_services: 'Кроме личных проектов я беру заказы в сфере производства 3D/2D графики: моделирование, анимация, концептинг, супервайзинг проекта. По вопросам сотрудничества пишите:',
    developer_title: 'О разработчике сайта - Александр Ткачев',
    developer_intro: 'Я — веб-разработчик с широким спектром навыков и настоящей страстью к созданию современных, функциональных и красивых сайтов. Мои компетенции охватывают всё: от проектирования удобного пользовательского интерфейса до реализации сложной логики на фронтенде и бэкенде.',
    developer_react: 'Специализируюсь на разработке сайтов и приложений на React — создаю динамичные и отзывчивые интерфейсы, которые работают быстро и корректно на любом устройстве. Но этим дело не ограничивается — я также занимаюсь дизайном, версткой, интеграцией API, SEO-оптимизацией, а иногда и полным стеком разработки «от идеи до результата».',
    developer_projects: 'Мне интересны как маленькие сайты-визитки, так и масштабные веб-приложения. Я всегда стремлюсь найти баланс между эстетикой и технической эффективностью, чтобы результат не только выглядел круто, но и работал без сбоев.',
    developer_contact: 'Если вам нужен разработчик, который понимает не только код, но и дизайн, умеет слушать клиента и предлагать решения — вы обратились по адресу.',
    contact_telegram: 'Связаться в Telegram',
    // Footer translations
    footer_brand_desc: 'Эксклюзивные товары от 2D/3D художника и аниматора Андрея Барщевского',
    footer_navigation: 'Навигация',
    footer_home: 'Главная',
    footer_catalog: 'Каталог',
    footer_about: 'О нас',
    footer_cart: 'Корзина',
    footer_contacts: 'Контакты',
    footer_social: 'Социальные сети',
    footer_copyright: '© 2025 Barsh Shop. Все права защищены.',
    order_website_button: 'Заказать сайт',
    // Cart page
    continue_shopping: "Продолжить покупки",
    items: "Товары",
    clear_cart: "Очистить корзину",
    by_clicking_you_agree: "Нажимая на кнопку, вы соглашаетесь с",
    privacy_policy: "Условиями обработки персональных данных",
    terms_of_sale: "Условиями продажи",
    and: "а также с"
  },
  en: {
    shop_name: 'Barsh Shop',
    catalog: 'Catalog',
    about: 'About',
    about_author: 'About Author',
    cart: 'Cart',
    home: 'Home',
    search_placeholder: 'Search products...',
    all_categories: 'All Categories',
    stickers: 'Stickers',
    keychains: 'Keychains',
    postcards: 'Postcards',
    figures_3d: '3D Figures',
    add_to_cart: 'Add to Cart',
    price_from: 'from',
    rubles: 'rub.',
    exclusive_stickers: 'Exclusive Stickers',
    from_andrey_barsh: 'from Andrey Barsh',
    hero_subtitle: 'Unique designs for your projects',
    featured_products: 'Featured Products',
    empty_cart: 'Cart is empty',
    total: 'Total',
    checkout: 'Checkout',
    quantity: 'Quantity',
    remove: 'Remove',
    about_title: 'About Barsh Shop',
    about_description: 'We specialize in creating unique stickers, keychains, postcards and 3D figures. Our designs are distinguished by high quality and originality.',
    items_in_cart: 'items in cart',
    // New translations
    new_collection: 'New Collection',
    hero_title: 'Exclusive designs from ',
    hero_brand: 'Barsh',
    hero_description: 'Discover unique stickers, keychains, postcards and 3D figures created with love and attention to detail.',
    shop_now: 'Shop Now',
    learn_more: 'Learn More',
    why_choose_us: 'Why Choose Us',
    features_subtitle: 'We offer the best quality and service',
    quality_products: 'Quality Products',
    quality_desc: 'All our products are made from high-quality materials',
    fast_delivery: 'Fast Delivery',
    delivery_desc: 'We deliver orders throughout Russia in the shortest time',
    secure_payment: 'Secure Payment',
    payment_desc: 'We guarantee the security of all payment transactions',
    featured_subtitle: 'The most popular products in our store',
    view_all: 'View All',
    view_product: 'View Product',
    back_to_catalog: 'Back to Catalog',
    description: 'Description',
    high_quality_materials: 'High-quality materials',
    unique_design: 'Unique design',
    fast_shipping: 'Fast shipping',
    satisfaction_guarantee: 'Quality guarantee',
    delivery_info: 'Delivery Information',
    free_delivery_over: 'Free delivery on orders over',
    delivery_time: 'Delivery time:',
    business_days: 'business days',
    return_policy: 'Return within',
    days: 'days',
    no_products_found: 'No products found',
    // Checkout translations
    checkout_title: 'Checkout',
    customer_info: 'Customer Information',
    first_name: 'First Name',
    last_name: 'Last Name',
    phone_number: 'Phone Number',
    email: 'Email',
    delivery_address: 'Delivery Address',
    city: 'City',
    enter_city: 'Enter city',
    street_address: 'Street Address',
    enter_address: 'Enter address',
    postal_code: 'Postal Code',
    map_placeholder: 'Map for address selection',
    address_selection: 'Select exact address on map',
    order_items: 'Order Items',
    order_summary: 'Order Summary',
    subtotal: 'Subtotal',
    delivery_cdek: 'CDEK Delivery',
    delivery_post: 'Russian Post Delivery',
    delivery_method: 'Delivery Method',
    out_of_servise: 'Temporarily Out Of Service',
    calculating: 'Calculating...',
    place_order: 'Place Order',
    // About page translations
    about_greeting: 'Hello! My name is Andrey Barshevsky',
    about_intro: 'My nickname is Barsh. I am a 2D/3D artist, animator and blog author, where I share my experience, work processes, thoughts about the industry and art.',
    about_location: 'I am from St. Petersburg. I started drawing in 2019, mastering academic drawing and painting for about 2 years in an art studio. At the same time I learned to work in Photoshop. It was then that I first opened Blender 3d.',
    about_school: 'In high school, I became interested in cameras and color correction. I took simple graphic design orders for social networks. I started learning After Effects, Premier pro, Davinci.',
    about_3d: 'In 2022, I resumed studying 3D graphics, some of my works began to gain views on Sketchfab and Artstation. Interesting orders appeared.',
    about_clients: 'First experience working with foreign clients.',
    about_youtube: 'I have been running a YouTube channel since 2023.',
    work_inspiration_title: 'My Work and Inspiration',
    work_intro: 'All my creativity is a mixture of 2D and 3D art. I like the process of creating visuals. Those that convey mood, possibly meaning or pleasure, when it comes to design.',
    work_simplicity: 'In drawing, I don\'t like using many technologies and tools. Sometimes one layer and a brush are enough. Through simplicity I preserve a piece of magic.',
    work_tools: 'But when working on 3D graphics or video production, I always look for the best combinations of tools.',
    work_inspiration: 'Everything that surrounds me and happens to me gives me inspiration. Personal experience is much more valuable. Based on it, you can develop new ideas.',
    work_services: 'In addition to personal projects, I take orders in the field of 3D/2D graphics production: modeling, animation, concepting, project supervision. For collaboration inquiries, write:',
    developer_title: 'About the Website Developer - Alexander Tkachev',
    developer_intro: 'I am a web developer with a wide range of skills and a real passion for creating modern, functional and beautiful websites. My competencies cover everything: from designing a convenient user interface to implementing complex logic on the frontend and backend.',
    developer_react: 'I specialize in developing websites and applications on React — I create dynamic and responsive interfaces that work quickly and correctly on any device. But it doesn\'t end there — I also do design, layout, API integration, SEO optimization, and sometimes full stack development "from idea to result".',
    developer_projects: 'I am interested in both small business card sites and large-scale web applications. I always strive to find a balance between aesthetics and technical efficiency, so that the result not only looks cool, but also works without failures.',
    developer_contact: 'If you need a developer who understands not only code, but also design, knows how to listen to the client and offer solutions — you have come to the right place.',
    contact_telegram: 'Contact via Telegram',
    // Footer translations
    footer_brand_desc: 'Exclusive products from 2D/3D artist and animator Andrey Barshevsky',
    footer_navigation: 'Navigation',
    footer_home: 'Home',
    footer_catalog: 'Catalog',
    footer_about: 'About',
    footer_cart: 'Cart',
    footer_contacts: 'Contacts',
    footer_social: 'Social Media',
    footer_copyright: '© 2025 Barsh Shop. All rights reserved.',
    order_website_button: 'Order Website',
    // cart Page
    continue_shopping: "Continue shopping",
    items: "Items",
    clear_cart: "Clear cart",
    by_clicking_you_agree: "By clicking the button, you agree to",
    privacy_policy: "Terms of processing personal data",
    terms_of_sale: "Terms of sale",
    and: "and also with"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<'ru' | 'en'>('ru');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['ru']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
